### ISSUE TITLE
HSV_To_RGB help needed

### ISSUE THREAD

**Issue by marcomameli1992** [kornia/kornia#1063]
Dear, I'm using your package to convert an image from RGB to HSV color space to use it has input. When I try to make the inverse convertion and save it with torchvision save image utils I obtain an image that is not equal to the real.
I use scikit-image to open the original image, after that I convert the opened image to tensor and apply the function rgb_to_hsv on it, in the saving stage I use hsv_to_rgb and after that use the output tensor for save_image function.

**Comment by justanhduc** [comment]
Hi @marcomameli1992. I didn't try yet but just to make sure, did you scale the input to between [0, 1]? Did you use `==` or `torch.isclose`? Since everything is floating point the former may result in "not equal" as you observed.

**Comment by edgarriba** [comment]
Was checking the tests and this is something that we should have to make the api consistent. I believe @cceyda tried that at some point

**Comment by cceyda** [comment]
@marcomameli1992 I understand you are doing rgb_to_hsv ->hsv_to_rgb and finding rgb!=rgb.

This can sometimes be because not all color conversions are exact inversible, cause some times we add epsilon values to avoid non differentiability issues. Nevertheless inversing conversions should still result in the same values (max differences within 1e-4)

Please look at the Kornia section of following notebook:
https://gist.github.com/cceyda/b66996de7bc80811aa6135f81d84309d
Also make sure your input RGB is a float tensor in [0,1] range.

But; as @edgarriba mentioned
There is an unnecessary epsilon at hsv conversion right now, which might effect this.
Also realized we don't have `test_forth_and_back` for hsv conversions.
This is simple enough I'll do a pr tomorrow.

**Comment by cceyda** [comment]
forgot about this 😅 Although there isn't a bug, there is some improvement to be made as I said before.
will add it to my list
