### ISSUE TITLE
RandomPerspective and RandomAffine fail when used wih pytorch-lightning precision=16

### ISSUE THREAD

**Issue by psandev** [kornia/kornia#1477]
### Describe the bug

HI,
I am using the following transform:
train_transforms = torch.nn.Sequential(
        K.augmentation.RandomHorizontalFlip(),
        K.augmentation.RandomPerspective(distortion_scale=0.02),
        K.augmentation.RandomAffine(degrees=(-5.0, 5.0), translate=(0.02, 0.02), scale=(0.9, 1.1), shear=(-0.02, 0.02),
                                 resample='bilinear'),
    )

pl version: 1.5.4
kornia version: 0.6,1
pytorch version: 1.9.1+cu111

The error is: RuntimeError: expected scalar type float but found c10::Half

### Reproduction steps

```bash
1.Create a simple PyTorch-lightning model
2.set precision=16 in the trainer parameters
3.
...
```

### Expected behavior

Support 16bit precision.

### Environment

```shell
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
- PyTorch Version (e.g., 1.0):
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:
```


### Additional context

_No response_

**Comment by edgarriba** [comment]
@psandev thanks for the feedback -- did a quick test here. To execute geometric transformations with half precision you need to use cuda because of the grid sampler not implemented for fp16 in cpu from  PyTorch side. My guess is that some logics under PL don't handle well your case @Borda 

Colab I used to verify: https://colab.research.google.com/drive/1JRwIreL075uqgWhO1WNccu4d7ry1H4Ro?usp=sharing

**Comment by Borda** [comment]
I think that the half-precision on CPU is a future PyTorch feature coming in 1.10

**Comment by psandev** [comment]
I used half-precision on GPU.

**Comment by apolinario** [comment]
I have the same issue on GPU

**Comment by edgarriba** [comment]
I just tried again with latest version this shared colab and it works for me: https://colab.research.google.com/drive/1JRwIreL075uqgWhO1WNccu4d7ry1H4Ro?usp=sharing

![image](https://user-images.githubusercontent.com/5157099/163795123-23839c6d-c76d-46c9-868e-47de4f511a0d.png)

i'd open a ticket in lightning. Otherwise you can try our training api -- i use at work and works well at least for vision projects. And soon we'll update with a more modern design specially for building more complex deployment/training pipelines for async applications like robotics.

**Comment by edgarriba** [comment]
Closing this -- unless you have a kornia specific non-working code please reopen. Otherwise touch base the lightning team in their channels.
