### ISSUE TITLE
[FEATURE] Rendering/rastering stuff

### ISSUE THREAD

**Issue by Daiver** [kornia/kornia#165]
Hi guys! Thank you for great library
Is there any plans to implement 3d model rendering/rastering? Probably like https://github.com/tensorflow/graphics

**Comment by edgarriba** [comment]
hi @Daiver ! kornia (torchgeometry before) and tf.graphics are quite overlapped.

Please, take a look at the geometry module since we already cover part of the camera api. Not real plans to introduce rendering/rastering at this very moment since we are refactoring some of the api and make the codi compliant with jit in order to be used in production. However, if you feel that you can contribute with it, just go ahead.

BTW, I like this: https://github.com/Daiver/pygeom_tools/blob/master/geom_tools/mesh.py
Should we join efforts ? :D

**Comment by Daiver** [comment]
@edgarriba thank you for your attention! it's super simple module for my own pet projects but I don't mind :) But i'm not sure that i have enough time.
Also i have super naive rasterization too, btw (somewhere).

**Comment by edgarriba** [comment]
@Daiver any update on this ?
