### ISSUE TITLE
More backends support

### ISSUE THREAD

**Issue by hipudding** [kornia/kornia#2736]
## 🚀 Feature

I'm wondering whether it's welcome to contribute more backends support?

## Motivation

There're more Accelerators except CUDA and CPU, I think awesome project like kornia can be used in more scenarios if more backends are support. I'd like to contribue one of them.

## Pitch

1. Abstract CUDA or MPS to DEVICE
2. Choose correct backends when kornia starting.
3. Run all features on this selected backends.

## Additional context

______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by edgarriba** [comment]
@hipudding thanks for reaching out. What other backends do you have in mind, and how those abstractions would look like ?

**Comment by hipudding** [comment]
I'd like to add [Ascend NPU](https://www.hiascend.com/en/) as a new backend. And I want to change any keywords like gpu,cuda to deivce or something else. Device mean the current backend I'm using.

**Comment by edgarriba** [comment]
@hipudding idk if you have checked the internals of kornia ? but by design our interfaces are quite agnostic to the device backend under the inputs tensors data. In case we want to explore and support this path, the first thing would be to put in place a ci workflow against `npu` hardware and see from there.

Besides, we tried a similar thing in the past with xla devices but we ended up hooked to gcp subscriptions plans and as a non-profit org we do not have resources/money to support ourselves the cost of that effort.

Let me know you thoughts, and feel free to join our slack to discuss more  with the team.

**Comment by hipudding** [comment]
Yes, I had a quick look of kornia's code, it's true most of the code are not aware of the hardware. Only exists a little bit places to change. That's why I thought it may possible to add a new backend with out change a lot of base code.

For the CI workflow or devices, I may be able to provide support, this is not a problem.

Since we are still investigating, all I want to know is whether it's welcome to contribute for a new backend. And I'd like to discuss more details though github or slack after a demo finished.

Thank you very much for your reply. Have a nice day.

**Comment by edgarriba** [comment]
thanks ! let us know

**Comment by hipudding** [comment]
Sure. I will.
