### ISSUE TITLE
[CI] collector job failling

### ISSUE THREAD

**Issue by johnnv1** [kornia/kornia#2944]
### Describe the bug

Our collector job, should pass when the previous required jobs pass, otherwise it should fail. Currently, I'm seen some weird failures by the collector job in the last PR's (#2040 #2041 #2043)

### Reproduction steps

```bash
Open/check recently PR's
```

### Expected behavior

works

### Environment

```shell
CI
```

**Comment by lappemic** [comment]
After reviewing the recent failures in PRs #2040, #2041, and #2043, I've noticed that some failures occure due to the tutorials job. Specifically, there appears to be a TurboJPEG error when executing the Jupyter notebooks. Here are some observations and potential solutions we could try:

1. The error occurs during the `make execute` step in the tutorials workflow.
2. It might be related to a missing system dependency (possibly libjpeg-turbo) that's not listed in our requirements files.
3. While `kornia-rs` (which likely uses TurboJPEG) is in our requirements.txt, the CI environment may be missing some necessary system libraries for image processing.

Some potential fixes we could experiment with:

1. We could try adding libjpeg-turbo as a system dependency in our CI workflow.
2. We might update the tutorials workflow to install any needed system dependencies before running the notebooks.
3. It might be worth reviewing our numpy version constraint (<=2.0.0) to see if it's causing any compatibility issues.
4. Adding more verbose output to the notebook execution step could help us diagnose issues more easily.

I'm not certain these changes will solve the problem. If you think these are worth pursuing, I'd be happy to work on implementing them and see if they help resolve the tutorial job errors.

**Comment by johnnv1** [comment]
> After reviewing the recent failures in PRs #2040, #2041, and #2043, I've noticed that some failures occure due to the tutorials job. Specifically, there appears to be a TurboJPEG error when executing the Jupyter notebooks. Here are some observations and potential solutions we could try:


Just as a note, the collector job starts falling before we have issues with the tutorials / or any other CI. But you have bring valid points, we need to fix the tutorials CI anyway. For now, I would say to try to pin the kornia-rs version on kornia/tutorials repo, because i think it's related with the latest release of it, which @edgarriba will take a look on the next days

**Comment by johnnv1** [comment]
as pointed out by @shijianjian in someplace -- the collector job is failing because it requires the `docs` which aren't bein executed
