### ISSUE TITLE
[Feature Request] Data Augmentation Module

### ISSUE THREAD

**Issue by dvd42** [kornia/kornia#298]
I will start implementing a data augmentation module in the library. WIth operators such as those that can be found in torchvision. This module will be basically a wrapper that adds some random factor to the existing functions in the library. I am opening this issue as a reference. Anyone who would like to contribute with some data augmentation functionalities is more than welcome to do so. :smiley: 

Features To Implement
 See #312

**Comment by edgarriba** [comment]
@dvd42 great ! feel free to create a separated branch for that. Can you create a list with all the operators you are planning to implement ?

**Comment by lferraz** [comment]
I think it is a good idea assume that the output of the augmentations is composed by 2 things; the augmented tensor and the applied transformation. The applied transformation is very useful to apply the transformation to the metadata (e.g. points or bounding boxes). Ideally all the basic transforms in the near future should provide this info if it is required.

**Comment by smounsav** [comment]
I like this idea and the way DA can be done in this library. In other libraries, they provide those random transformations functions but not always the basic functions, so you can t learn the parameters or apply specific transformations. In kornia there would be both, and so that people can choose between specific transformations or random ones.

**Comment by edgarriba** [comment]
@dvd42 check roadmap. It's been decided that we will align other frameworks API like albumentations, torchvision and provide differentiable versions of the augmentation functions as discussed too here. So let's do a bit a of research and update the functionalities.

Besides, as discussed too we might want to return the transforms.  For that I would make it optional and provide a boolean  `return_transform` flag. In a addition, what about when we concatenate transforms ? Should we concatenate transforms ? `new_tf = prev_tf @ curr_tf`

**Comment by lferraz** [comment]
Automatic concatenation could be fantastic, however that means that all the transforms need this flag.
Do you want to add this flag to all the transforms? another option could be adding a wrapper doing this multiplication and assuming that if a transform doesn’t provide a matrix is because the matrix is the identity.

**Comment by edgarriba** [comment]
@lferraz probably in order to keep the API clean and simple is just to return the transform if and only if the user specify that using a flag `return_transformation` similar to [`nn.MaxPool`](https://pytorch.org/docs/stable/nn.html#torch.nn.MaxPool2d). In case a user wants to concatenate a transform should be pretty straightforward, we can even provide examples for that. In this way, we give enough flexibility to the user to perform challenging data transformations and we avoid potential nightmares in terms of maintenance.

**Comment by lferraz** [comment]
Perfect!!

**Comment by edgarriba** [comment]
close this since the module is already there. @dvd42  could you bootstrap a bit the main and missing functionalities ?
