### ISSUE TITLE
Antialiasing issues (max_blur_pool)

### ISSUE THREAD

**Issue by VRandme** [kornia/kornia#426]
Hello I have submitted a minor pull request regarding max_blur_pool.py

It Involves no actual code changes and only touches the comments so I believe it should be no problem to pull.
https://github.com/kornia/kornia/pull/425

Also, the output shape currently states
Output: :math:`(B, C, H / 2, W / 2)`

However, when i use the example code with varying kernel sizes(2,3,4 etc)
the output sizes may or may not be as stated above.
More specifically, with odd numbered kernels(3,5,7 etc) the above is true
but not for even numbered kernels(2,4,6,8 etc) 
Considering the scarcity of even numbered kernels, this might be intended behavior,
But I would appreciate further clarification in the documents.

I discovered these issues while trying to implement ConcatBlurpool which concatenates the results of MaxBlurPool and the self explanatory AvgBlurPool

I wanted to implement something similar to fastai's AdaptiveConcatPool2d
(https://docs.fast.ai/layers.html#AdaptiveConcatPool2d)
which concatenates the results of maxpool and avgpool for higher accuracy with minimal overhead.

I am almost done with my implementation of AvgBlurPool and ConCatPool
(very simple implementation that changes minor details from the original max_blur_pool)

If the maintainers of kornia would like the code, i will make a pull request.

**Comment by edgarriba** [comment]
@VRandme thanks for the feedback. I'ts okay from my side. @ducha-aiki has been playing with this layer, maybe he has more to add to the conversation.

**Comment by ducha-aiki** [comment]
@VRandme sure, go ahead with PR.

 Regarding the function itself, unlike the standard blurs (MaxPool, AvgPool), this one has weakly decoupled Pooling (weighted sum, or how you would like to call it) and the subsampling step, which is now done by pyrdown, so can be only 2x, 4x and so on. The problem you are experiencing is that polling now does not have  padding like the convolution, so the problems arise. Moreover, it is hard to decide how to pool with even kernels, because padding will be asymmetrical.
One solution would be first pool, then use F.interpolate back to the desired size. The drawback is significant slow down. 

Second consideration is the MaxPoolBlur is doing the antialiasing when subsumpling. But when you do global pooling, then it looses its benefits and GeM pooling is probably better solution.

**Comment by edgarriba** [comment]
@ducha-aiki @VRandme any possible actions here ? Otherwise let's keep this conversation closed.
