### ISSUE TITLE
Video processing

### ISSUE THREAD

**Issue by shirgur** [kornia/kornia#492]
I want to apply transformations on a sequence of video frames ```(BTCHW)```.
1) Looks like it is not possible for that form of tensor
2) If I apply RandomSOMETHING, on a single sequence ```(TCHW)```, each frame transforms differently

Is there a solution?
Thanks

**Comment by edgarriba** [comment]
@shirgur thanks for pointing out this use case. At this moment I believe it's not possible with the high level API since we assume `BCHW` for every single operator in Kornia. However, we will think how to adapt the API for augmenting videos.

The only thing I can think about now is manually generating the parameters based on the batch size, replicate over channels size and finally use `*_apply_*` functional found under kornia.augmentation. /cc @shijianjian

**Comment by shijianjian** [comment]
Hi @shirgur,

1. For now, we only support BCHW.

2. The temp workaround can refer to https://github.com/kornia/kornia/issues/476#issuecomment-601984118.

Apology here since we got two different mechanisms of parameter generating while development. You may use:
```python
rot = RandomRotation(360)
param = RandomRotation.get_params(batch_size, 360)
rot(TCHW, param)
```
or
```python
rot = ColorJitter(1, 1, 1, 1)
rot.set_param(batch_size, 1, 1, 1, 1)
rot(TCHW, rot._params)
```
Please refer to https://github.com/kornia/kornia/blob/master/kornia/augmentation/augmentation.py for details.

**Comment by shijianjian** [comment]
Close via #482 with ```same_on_batch``` functionality.
