### ISSUE TITLE
Allow pytorch 1.5.1 in requirements

### ISSUE THREAD

**Issue by hal-314** [kornia/kornia#584]
## 🐛 Bug

Kornia force pytorch 1.5.0 version

## To Reproduce

Install kornia ;)

## Expected behavior

Allow to use pytorch 1.5.1 or >= 1.5 

## Additional context

You could do it by changing this line in requirements.txt
`pytorch==1.5.0 `
to 
`pytorch==1.5.*` or `pytorch>=1.5` (to allow any future pytorch versions
**Note**: I didn't tested the change.

**Comment by theRealSuperMario** [comment]
I agree that just `pip install kornia` is not working as inteded. I don't want my pytorch version to change when installing the library. So maybe just release a table which gives installation instructions for the last 3 pytorch versions?

**Comment by shijianjian** [comment]
It makes sense, @edgarriba Can we maintain different PyTorch versions using some like ```torch.__version__```? We can have a minimum required version, say started from 1.2.0 or so.

**Comment by edgarriba** [comment]
as a policy we update pytorch version each major or minor release and not patch release, since our development resources is not as big as other teams.

@shijianjian if we figure out a proper mechanism to track versioning down, I would be fine with it. In theory each kornia release is aligned with the corresponding last pytorch minor release.

@theRealSuperMario take into account the pip it's not the best solving versioning conflicts.

we are planning a patch release as well within the next couple of weeks. We can work here for a first proposal for handling versioning before the next minor release.

**Comment by gohar-malik** [comment]
@edgarriba For now you can set it up in a way, that it also changes the torchvision version to the one compatible with torch 1.5.0. Because when someone installs kornia it forces torch=1.5.0, which makes the already installed torchvision incompatible, specially when someone's also using cuda.

**Comment by edgarriba** [comment]
probably the best way is to update this [line](https://github.com/kornia/kornia/blob/master/setup.py#L79) by
`pytorch_dep += "=" + os.getenv('PYTORCH_VERSION')`

and each time we release specify just MAJOR and MINOR versions.

e.g. PYTORCH_VERSION=1.6 with single equal operator, pip should be able to handle future PATCH releases *but not recommended since for now we are not going to test/support PATCH releases.

**Comment by theRealSuperMario** [comment]
That's a great idea. For now, I just removed the dependency and wrote down how to set it up

```
# torch==1.5.x
pip install git+https://github.com/therealsupermario/kornia@fix/fixed_requirement
# torch==1.4.x
pip install git+git://github.com/kornia/kornia.git@v0.2.2
```

https://github.com/theRealSuperMario/kornia/tree/fix/fixed_requirement

**Comment by edgarriba** [comment]
closing, this should be in fixed in the lateast release

**Comment by swsongwei** [comment]
now, my conda env as follows:
![image](https://user-images.githubusercontent.com/44295578/226233308-0830fc19-fd54-4639-afe8-6cb375f37aca.png)
and we can use kornia==0.6.4 when the version of pytorch==1.9.0 is not changed.
![image](https://user-images.githubusercontent.com/44295578/226233503-dbea841f-0c0a-4be2-8417-370052cc4b12.png)
and the version of pytorch will be changed if we use pip install kornia, which is the latest kornia.
