### ISSUE TITLE
Expose RandomCrop interpolation API

### ISSUE THREAD

**Issue by versatran01** [kornia/kornia#617]
## 🐛 Bug

I noticed that random crop interpolation mode is fixed to bilinear, when I try to crop a depth map with zeros, it generates nonzero values which are undesired. Happens to center crop as well.

Also I don't understand why this simple crop operation requies interpolation (when size is just an int)?

**Comment by edgarriba** [comment]
@versatran01 thanks for asking. Let me answer both questions:

1) We use bilinear interpolation since torch grid_sample has this parameter set by default. I think we can expose other interpolation methods to this operator. /cc @shijianjian 

2) RandomCrop does not generate simple random integers to define the cropping boxes. We also want to make full use of differentiability and grid_sample doesn't support yet non floating point precision.

**Comment by shijianjian** [comment]
[```torch.grid_sample()```](https://pytorch.org/docs/stable/nn.functional.html#torch.nn.functional.grid_sample) supports only nearest and bilinear. They are all supported in the current version.

@versatran01 Since our current implementation is based on perspective transforms, the issue you described indeed exists. As @edgarriba said, our implementation was trying to keep the differentiability. We will see what we can do to improve it to the desired output.

**Comment by shijianjian** [comment]
For a temperate solution, you may use ```align_corners=True```. It will occasionally occur non-zero values (mostly smaller than 1e-5). Hope it may be sufficient for your projects.

**Comment by versatran01** [comment]
My solution currently is to use generate_param and then change interpolation to 0 manually.

**Comment by shijianjian** [comment]
Added in #633.
