### ISSUE TITLE
[Bug] Mismatched input and output shapes in Augmentations

### ISSUE THREAD

**Issue by justanhduc** [kornia/kornia#721]
## To Reproduce

Simply applying `ColorJitter` to an RGB image would produce the batch version.
First discussion was [here](https://github.com/kornia/kornia/issue_comments/708281134).

```
>>> import torch
>>> from kornia.augmentation import ColorJitter
>>> x = T.rand(3, 4, 4)
>>> cj = ColorJitter(0.2, 0.3, 0.2, 0.3)
>>> cj(x).shape
torch.Size([1, 3, 4, 4])
```

## Expected behavior

Output should have the same shape as input.

## Additional context

Maybe it is the originally intended behavior, but I think it is too rigid and deeply integrated into training deep NN, while the goal of Kornia is a differentiable OpenCV in GPU.
Or am I missing anything here?

Edit 2: Added link to the original discussion.

**Comment by shijianjian** [comment]
Not only ColorJitter. All augmentations were designed to input everything then output BCHW for 2D, BCDHW for 3D. It could be very straightforward if updating the code in ```_AugmentationBase```.

Since it gonna change a lot of behaviours, we shall discuss it first.

@edgarriba, @FGeri , @ducha-aiki What are you guys thinking? Shall we update the code to align the input shape?

**Comment by edgarriba** [comment]
I would return always the same shape as the input.

**Comment by FGeri** [comment]
I'd also go for not changing the shape.

**Comment by shijianjian** [comment]
@justanhduc Please go-ahead for a PR if you are okay to do so!

**Comment by justanhduc** [comment]
Ok I will try to work on it asap.

**Comment by shijianjian** [comment]
Cloased by #731
