### ISSUE TITLE
[Bug] Wrongly overwrite the same torch version with different CUDA versions

### ISSUE THREAD

**Issue by shijianjian** [kornia/kornia#729]
## 🐛 Bug

In my machine, I use torch+cu101. But if run ```pip install kornia```, it will re-install the torch, but I actually need torch+cu101. It is better to ignore the suffix CUDA labels whilst running.

## Expected behavior

It should not overwrite torch despite the CUDA versions.

**Comment by pmeier** [comment]
Unfortunately, this is something this is not something that can be handled from within a package such as `kornia`. In short: PyPI, the default repository for `pip`, cannot differentiate between computation backends such as `cpu`, `cu102`, and so on. Thus, only the version of the current CUDA release will be uploaded to PyPI and a default `pip install` will install that. If you need PyTorch for another computation backend such as `cu101` you need to manually install it from [their instructions](https://pytorch.org/get-started/locally/).

Since this is very cumbersome and you have to do the version resolving yourself, I created [`light-the-torch`](https://github.com/pmeier/light-the-torch). It is a drop-in replacement for `pip install` and handles the computation backend for you. With it installing `kornia` is as easy as:

```sh
pip install light-the-torch
ltt install kornia
```

Let me know if this solves your issue or if you have further questions.

**Comment by shijianjian** [comment]
What I mean is I have already using the correct version of torch, say `torch==1.6.0+cu101`, but it will be overwritten to `torch==1.6.0`. We should somehow make pip recognize 1.6.0+cu101 to be 1.6.0.

**Comment by pmeier** [comment]
Nope. If it was overwritten, you did something else.

``` sh
$ pip install -f https://download.pytorch.org/whl/torch_stable.html torch==1.6.0+cpu
[...]
Successfully installed future-0.18.2 numpy-1.19.2 torch-1.6.0+cpu
$ pip install torch
Requirement already satisfied: torch in ./.venv/lib/python3.6/site-packages (1.6.0+cpu)
[...]

**Comment by shijianjian** [comment]
Can we fix this dependency problem in setup.py? we need to somehow let pip ignore the cu101 suffix and treating `1.6.0+cu101` as the correct version.

**Comment by pmeier** [comment]
> we need to somehow let pip ignore the cu101 suffix and treating `1.6.0+cu101` as the correct version.

Not sure if I understand you correctly, but `pip` does exactly that. If you install `torch==1.6.0+cu101` in a first step and only `pip install kornia` afterwards, it will accept the already installed version of `torch`.

**Comment by shijianjian** [comment]
Yes. I was stupid. I used "pip install --force-reinstall kornia", which will reinstall the torch version from 1.6.0+cu101 to 1.6.0.
