### ISSUE TITLE
Why not JIT all modules?

### ISSUE THREAD

**Issue by justanhduc** [kornia/kornia#751]
## 🚀 Feature
All modules when applicable can be jitted for performance.

## Motivation

Modules can be jitted for performance. An inspiration is [here](https://github.com/rusty1s/pytorch_scatter/blob/134b5c75ec5f9200ab509615071ff1ddd265e78b/torch_scatter/scatter.py#L8).

## Pitch

The code may look like this.

```
@torch.jit.script
def random_hflip(input: torch.Tensor, p: float = 0.5, return_transform: bool = False
                 ) -> Union[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]:
    ...
```

**Comment by edgarriba** [comment]
@justanhduc I don't think we are able to support at this point for augmentations since our return type is a conditional tuple and I believe this is not supported by torchscript itself. However, supporting torchscript for kornia core it's one of the milestones for v0.5 for next month. See: https://github.com/kornia/kornia/issues/739

**Comment by edgarriba** [comment]
discussed in https://github.com/kornia/kornia/issues/941
