### ISSUE TITLE
angle_axis_to_quaternion returns (w, x, y, z) instead of (x, y, z, w)

### ISSUE THREAD

**Issue by amonszpart** [kornia/kornia#903]
https://github.com/kornia/kornia/blob/b5418d8bac9e7bb01e66310d7d2b4227766c5a02/kornia/geometry/conversions.py#L682

```python
def angle_axis_to_quaternion(angle_axis: torch.Tensor) -> torch.Tensor:
    r"""Convert an angle axis to a quaternion.
    The quaternion vector has components in (x, y, z, w) format.               # <-- says (x, y, z, w)
    # ...
    return torch.cat([w, quaternion], dim=-1)                                  # <-- does (w, x, y, z)
```

proposal:
```python
return torch.cat([quaternion, w], dim=-1)
```

Similarly, in [quaternion_to_angle_axis](https://github.com/kornia/kornia/blob/b5418d8bac9e7bb01e66310d7d2b4227766c5a02/kornia/geometry/conversions.py#L529):
```python
q1: torch.Tensor = quaternion[..., 0]
q2: torch.Tensor = quaternion[..., 1]
q3: torch.Tensor = quaternion[..., 2]
```

**Comment by edgarriba** [comment]
@amonszpart could you send a PR with this proposal ?

**Comment by schuhschuh** [comment]
Hi, also just wanted to report this. However, my conclusion is different in that I think the docstring should simply be fixed, not the code because the proposed code change would break existing code that relied on the implementation rather than the documentation. Also note that Ceres uses the convention ``(w, x, y, z)`` as well as noted in the docstring (see [here](https://github.com/ceres-solver/ceres-solver/blob/66b4c33e817ec34d64c7513950e74a3382e06662/include/ceres/rotation.h#L248-L275)). Moreover, a few papers on quaternions also use the adapted convention (for example [Joan Solà](https://arxiv.org/abs/1711.02508) and [Hartley et al.](https://t.co/9E8VLdG5md?amp=1)).

**Comment by amonszpart** [comment]
Proposed fix: https://github.com/kornia/kornia/pull/926

Re "fix the documentation": other quaternion functions follow the `(x, y, z, w)` convention (rotation_matrix_to_quaternion, quaternion_to_rotation_matrix, quaternion_log_to_exp, quaternion_exp_to_log), so those would need changing then.

**Comment by schuhschuh** [comment]
I didn't realize the convention was inconsistent with other quaternary related functions in kornia itself. In this case this should be flagged as bug maybe rather than enhancement?

**Comment by edgarriba** [comment]
@amonszpart @schuhschuh let's follow ceres convention [w, x, y, z] - we should also explain somewhere in the docs quaternion definition. There was even a proposal from  @versatran01 to have a separated module similar to [pyquaternion](http://kieranwynn.github.io/pyquaternion/).
