### ISSUE TITLE
[Feat] Add Sharpening to image tensors

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#937]
## 🚀 Feature
Implement some functionalities for sharpening

https://visp-doc.inria.fr/doxygen/visp-daily/group__group__imgproc__sharpening.html#ga2a67826689095b0d872ba469ebfc1242

**Comment by AnimeshMaheshwari22** [comment]
Hello! I would like to work on this

**Comment by lferraz** [comment]
Hi @AnimeshMaheshwari22 

thank you so much for your interest. The most basic algorithm is [this one](https://en.wikipedia.org/wiki/Unsharp_masking#:~:text=Unsharp%20masking%20(USM)%20is%20an,mask%20of%20the%20original%20image.). Of course it needs to be optimised for GPU. 

In the bibliography there are other methods based on the basic one, feel free to propose the one you want to contribute.

In fact, this issue is partially related with #702 and looks like there are nice approaches combining both Unsharp masking and Bilateral Filter.

**Comment by AnimeshMaheshwari22** [comment]
Hello @lferraz. I read about both, Bilateral filter and unsharp masking and have a query.  Wouldn't Bilateral filter suffice? Would like to have your guidance on this.

**Comment by AnimeshMaheshwari22** [comment]
Hello @lferraz. I read about both, Bilateral filter and unsharp masking and have a query. Wouldn't Bilateral filter suffice? Would like to have your guidance on this.

**Comment by lferraz** [comment]
hi @AnimeshMaheshwari22 ,
I think we can start with the unsharp mask, looks like it is only a convolution with a specific filter. 
 0 -1  0
-1  5 -1
 0 -1  0

And afterwards we can continue with the Bilateral one. 😃

**Comment by edgarriba** [comment]
@AnimeshMaheshwari22 I suggest you to look at filters module and expand the Kernels API with that one too

**Comment by AnimeshMaheshwari22** [comment]
> hi @AnimeshMaheshwari22 ,
> I think we can start with the unsharp mask, looks like it is only a convolution with a specific filter.
> 0 -1 0
> -1 5 -1
> 0 -1 0
> 
> And afterwards we can continue with the Bilateral one. 😃

Hello. Definitely. I would like to work on a PR for this. Also, I have a doubt. The approach for unsharp mask is orignal_image+(orignal_image-blur)*weight and here Gaussian blur can be used right? Also Gaussian blur is already implemented in kornia filters right?

**Comment by edgarriba** [comment]
merged in https://github.com/kornia/kornia/pull/1004
